;WITH CTE AS
(SELECT 
(CASE WHEN NUM_COUNT = 0 THEN NULL ELSE NUM END)  AS [NUM_VALUE] FROM
(
SELECT NUM, 
CASE WHEN COUNT(NUM) = 1 THEN COUNT(NUM) ELSE 0 END AS [NUM_COUNT]
FROM MyNumbers
group by num
)
T
)
SELECT TOP 1 NUM_VALUE AS num FROM CTE ORDER BY NUM_VALUE DESC;